apiVersion: v1
kind: Service 
metadata: 
  name: node-port
  namespace: meteapp
spec:
  selector:
    app: todolist
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30009
  type: NodePort